### ISSUE TITLE
How to register label using the output affine transformation?

### ISSUE THREAD

**Issue by John1231983** [ntustison/antsRegistrationWithMaskExample#1]
First of all, great thanks to your shell. I will put more than one star if it is possible :)

I have brain image (fixed image): T1, T2 and label1. I also have another brain image(moving image): T1,T2, and label2. The T1 and T2 in same subject have been alignedNow, I want to align two subject together and I found your shell. It is very help full and it worked. I have register T1 image in moving image to T1 image in fixed image and the output is

```
./OutputNoMask/ants0GenericAffine.mat
./ants1InverseWarp.nii.gz
./ants1Warp.nii.gz
./antsInverseWarped.nii.gz
./OutputNoMask/antsWarped.nii.gz 
```

Now, I want to register the T2 in moving image to T2 in fixed image and label2 in moving image to label1 in the fixed image using the above transformation. How should I do? Do I need to convert the label value (from 0 to 8) to float number likes (0:0.0-->0.2, 1:1.0-->1.2....) and perform registeration? Thanks so much

This is my current solution but the label did not align

```
affineTransformImage=/OutputNoMask/ants0GenericAffine.mat
warpImage=/OutputNoMask/ants1Warp.nii.gz
input_label=/brain/seg.nii.gz
ref_imgage=/brain/t1_fixed.nii.gz
outputDirectory=./OutputNoMask
mkdir -p $outputDirectory

antsApplyTransforms -d 3 -i ${input_label} \
  -o ${outputDirectory}/labelwarp.nii.gz \
  -t  ${affineTransformImage}\
  -r ${ref_imgage} 
```

**Comment by ntustison** [comment]
Try the following:

```
#warp moving T2 to fixed space

antsApplyTransforms -d 3 -i ${movingT2} -r ${fixedT1} -o ${warpedMovingT2} -n linear -t ants1Warp.nii.gz -t ants0GenericAffine.mat

# warp moving labels to fixed space

antsApplyTransforms -d 3 -i ${movingLabel} -r ${fixedT1} -o ${warpedMovingLabel} -n GenericLabel[Linear] -t ants1Warp.nii.gz -t ants0GenericAffine.mat
```

**Comment by John1231983** [comment]
@ntustison You saved my life. Could you ask you one more about parameters setting for 3D images. I changed your command to this one to work on 3D (deleted -r option). Anything else? Thanks

```
antsRegistration -d 3 -v 1 \
  -o [${outputDirectory}/ants,${outputDirectory}/antsWarped.nii.gz,${outputDirectory}/antsInverseWarped.nii.gz] \
  -t SyN[0.1,3,0] \
  -c [100x75x20x0,0,10] \
  -m CC[${fixedImage},${movingImage},1,4] \
  -f 4x3x2x1 \
  -s 1x1x0x0

```

**Comment by ntustison** [comment]
That'll do a SyN-only registration (e.g., no linear mappings).  You might want to use the scripts ``antsRegistrationSyNQuick.sh`` and ``antsRegistrationSyN.sh``.

**Comment by John1231983** [comment]
@ntustison : Very amazing with the script. It worked so well. 
If I have a T1 brain image and segmentation class (label from 0 to 8) likes mrbrains18. Do you think the  `Mask images` (-r) will be useful (more accurate??)? Do I need to convert the segmentation class to mask images before using -r (convert 8 classes to 2 classes:0-1)? Thanks

**Comment by ntustison** [comment]
> If I have a T1 brain image and segmentation class (label from 0 to 8) likes mrbrains18. Do you think the Mask images (-r) will be useful (more accurate??)?

Not sure.  You should test it out and determine for yourself.

> Do I need to convert the segmentation class to mask images before using -r (convert 8 classes to 2 classes:0-1)?

No.  The mask is any voxel != 0.
